# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VP6o6gxnVh8cfG97ce2isbg_GCOqOL-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from google.colab import files

# This will create an "Upload" button right inside your notebook
print("Please upload your IRIS.csv file below:")
uploaded = files.upload()

# Load the uploaded dataset dynamically
df = pd.read_csv('IRIS.csv')

# Look at the data structure to confirm it works
print("\nDataset Overview:")
print(df.head())

# Separate features (X) and target species (y)
X = df.drop(columns=['species'])
y = df['species']

# Encode flower names (Iris-setosa, etc.) to numbers (0, 1, 2)
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# Split into 80% Training data and 20% Testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features (Crucial for SVM to find the best boundary)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data successfully prepared and scaled!")

# Initialize the Support Vector Classifier with a linear kernel
svm_model = SVC(kernel='linear', random_state=42)

# Train the model on our scaled training data
svm_model.fit(X_train_scaled, y_train)

# Make predictions on the test data
y_pred = svm_model.predict(X_test_scaled)

# Print the final performance results
accuracy = accuracy_score(y_test, y_pred)
print(f"=== SVM Model Accuracy: {accuracy * 100:.2f}% ===\n")

print("=== Detailed Classification Report ===")
print(classification_report(y_test, y_pred, target_names=encoder.classes_))

# Generate and plot a confusion matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=encoder.classes_, yticklabels=encoder.classes_)
plt.title('SVM Classification Confusion Matrix')
plt.ylabel('Actual Species')
plt.xlabel('Predicted Species')
plt.show()